package com.example.safesteps;

import android.app.*;
import android.app.admin.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.os.*;
import android.provider.Settings;
import android.text.InputType;
import android.view.*;
import android.widget.*;

public class MainActivity extends Activity {
 public static final String PREFS="safe_steps",PASSWORD="admin_password",TYPE="password_type",ENABLED="protection_enabled",PIN="pin",PATTERN="pattern";
 private boolean authed=false,settingsLaunch=false; private LinearLayout body; private TextView status;
 @Override protected void onCreate(Bundle b){super.onCreate(b);init();authenticate();}
 private void init(){SharedPreferences p=getSharedPreferences(PREFS,0);if(!p.contains(PASSWORD))p.edit().putString(PASSWORD,"1234").putString(TYPE,PIN).putBoolean(ENABLED,false).apply();}
 @Override protected void onResume(){super.onResume();if(settingsLaunch){settingsLaunch=false;return;}if(authed)showManager();}
 private void authenticate(){authed=false;if(PATTERN.equals(getSharedPreferences(PREFS,0).getString(TYPE,PIN)))patternAuth();else pinAuth();}
 private LinearLayout root(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(28),dp(25),dp(28),dp(30));r.setBackground(grad(new int[]{Color.rgb(7,29,64),Color.rgb(34,112,188),Color.rgb(61,46,130)},0));TextView i=txt("🛡",70,Color.WHITE,true);i.setGravity(Gravity.CENTER);r.addView(i,new LinearLayout.LayoutParams(-1,dp(100)));TextView t=txt("אימות מנהל",30,Color.WHITE,true);t.setGravity(Gravity.CENTER);r.addView(t,new LinearLayout.LayoutParams(-1,dp(55)));TextView s=txt("רק מנהל מורשה יכול להיכנס",16,Color.WHITE,false);s.setGravity(Gravity.CENTER);r.addView(s,new LinearLayout.LayoutParams(-1,dp(45)));return r;}
 private void pinAuth(){LinearLayout r=root();EditText in=new EditText(this);in.setHint("סיסמת מנהל");in.setTextColor(Color.WHITE);in.setHintTextColor(Color.LTGRAY);in.setTextSize(21);in.setGravity(Gravity.CENTER);in.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);r.addView(in,new LinearLayout.LayoutParams(-1,dp(65)));Button b=btn("אימות");r.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));b.setOnClickListener(v->{if(getSharedPreferences(PREFS,0).getString(PASSWORD,"1234").equals(in.getText().toString()))open();else in.setError("סיסמה שגויה");});setContentView(r);in.requestFocus();getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);}
 private void patternAuth(){LinearLayout r=root();PatternLockView p=new PatternLockView(this);r.addView(p,new LinearLayout.LayoutParams(dp(300),dp(300)));Button b=btn("אימות");r.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));b.setOnClickListener(v->{if(getSharedPreferences(PREFS,0).getString(PASSWORD,"").equals(p.getPattern()))open();else{Toast.makeText(this,"תבנית שגויה",Toast.LENGTH_SHORT).show();p.clearPattern();}});setContentView(r);}
 private void open(){authed=true;showManager();}
 private void showManager(){ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(Color.rgb(245,248,252));body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(18),dp(20),dp(28));scroll.addView(body);TextView title=txt("Safe Steps",32,Color.rgb(20,43,76),true);title.setGravity(Gravity.CENTER);body.addView(title,new LinearLayout.LayoutParams(-1,dp(58)));TextView sub=txt("צעדים בטוחים בשבילך",17,Color.rgb(91,105,126),false);sub.setGravity(Gravity.CENTER);body.addView(sub,new LinearLayout.LayoutParams(-1,dp(38)));
  LinearLayout pc=card();status=txt("",21,Color.rgb(20,43,76),true);pc.addView(status,new LinearLayout.LayoutParams(-1,dp(48)));String ct=getSharedPreferences(PREFS,0).getString(TYPE,PIN);TextView type=txt(PATTERN.equals(ct)?"סוג סיסמה: קווים":"סוג סיסמה: מספרית",16,Color.rgb(91,105,126),false);pc.addView(type,new LinearLayout.LayoutParams(-1,dp(38)));Button toggle=btn("שינוי מצב ההגנה");pc.addView(toggle,new LinearLayout.LayoutParams(-1,dp(54)));toggle.setOnClickListener(v->credential("שינוי מצב ההגנה",()->{boolean e=getSharedPreferences(PREFS,0).getBoolean(ENABLED,false);getSharedPreferences(PREFS,0).edit().putBoolean(ENABLED,!e).apply();refresh();}));body.addView(pc,lp());
  LinearLayout actions=card();Button admin=btn("מנהל מכשיר");actions.addView(admin,new LinearLayout.LayoutParams(-1,dp(54)));admin.setOnClickListener(v->credential("מנהל מכשיר",this::admin));Button acc=btn("שירות ההגנה");actions.addView(acc,new LinearLayout.LayoutParams(-1,dp(54)));acc.setOnClickListener(v->{settingsLaunch=true;try{startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));}catch(Exception ignored){}});body.addView(actions,lp());
  LinearLayout options=card();TextView ot=txt("⋮  אפשרויות נוספות",21,Color.rgb(20,43,76),true);ot.setGravity(Gravity.CENTER);options.addView(ot,new LinearLayout.LayoutParams(-1,dp(48)));TextView os=txt("ניהול סיסמה ומידע על האפליקציה",14,Color.rgb(91,105,126),false);os.setGravity(Gravity.CENTER);options.addView(os,new LinearLayout.LayoutParams(-1,dp(32)));
  LinearLayout pass=optionCard("🔐","בחירת סיסמה","שינוי סוג הסיסמה והגדרת סיסמה חדשה");LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(82));pp.topMargin=dp(8);options.addView(pass,pp);pass.setOnClickListener(v->credential("אימות מנהל",this::chooseType));
  LinearLayout about=optionCard("ℹ","אודות","מידע על Safe Steps ופרטי האפליקציה");LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(82));ap.topMargin=dp(10);options.addView(about,ap);about.setOnClickListener(v->about());body.addView(options,lp());refresh();setContentView(scroll);}
 private void refresh(){if(status==null)return;boolean e=getSharedPreferences(PREFS,0).getBoolean(ENABLED,false);status.setText(e?"● ההגנה פעילה":"● ההגנה כבויה");status.setTextColor(e?Color.rgb(13,151,91):Color.rgb(211,75,65));}
 private void credential(String title,Runnable ok){String type=getSharedPreferences(PREFS,0).getString(TYPE,PIN);if(PATTERN.equals(type)){PatternLockView p=new PatternLockView(this);AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setMessage("ציירו את התבנית").setView(p).setNegativeButton("ביטול",null).setPositiveButton("אישור",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(getSharedPreferences(PREFS,0).getString(PASSWORD,"").equals(p.getPattern())){d.dismiss();ok.run();}else Toast.makeText(this,"אימות נכשל",Toast.LENGTH_SHORT).show();}));d.show();}else{EditText in=new EditText(this);in.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setMessage("הזינו את סיסמת המנהל").setView(in).setNegativeButton("ביטול",null).setPositiveButton("אישור",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(getSharedPreferences(PREFS,0).getString(PASSWORD,"1234").equals(in.getText().toString())){d.dismiss();ok.run();}else in.setError("אימות נכשל");}));d.show();}}
 private void chooseType(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(8),dp(18),dp(8));TextView d=txt("בחרו כיצד תרצו להגן על מנהל Safe Steps",16,Color.rgb(91,105,126),false);d.setGravity(Gravity.CENTER);c.addView(d,new LinearLayout.LayoutParams(-1,dp(48)));LinearLayout pin=passwordTypeCard("123","סיסמה מספרית","קוד מספרי שקל להזין"),pat=passwordTypeCard("✦","סיסמת קווים","ציור תבנית על גבי 9 נקודות");c.addView(pin,new LinearLayout.LayoutParams(-1,dp(86)));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(86));pp.topMargin=dp(12);c.addView(pat,pp);final boolean[] sel={false};pin.setOnClickListener(v->{sel[0]=false;selectPasswordCard(pin,false);selectPasswordCard(pat,true);});pat.setOnClickListener(v->{sel[0]=true;selectPasswordCard(pin,true);selectPasswordCard(pat,false);});selectPasswordCard(pin,false);selectPasswordCard(pat,true);AlertDialog dlog=new AlertDialog.Builder(this).setTitle("בחירת סוג סיסמה").setView(c).setNegativeButton("ביטול",null).setPositiveButton("המשך",null).create();dlog.setOnShowListener(x->dlog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{dlog.dismiss();if(sel[0])newPattern();else newPin();}));dlog.show();}
 private LinearLayout passwordTypeCard(String icon,String title,String sub){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(18),dp(10),dp(18),dp(10));TextView i=txt(icon,28,Color.rgb(40,125,225),true);i.setGravity(Gravity.CENTER);c.addView(i,new LinearLayout.LayoutParams(dp(60),-1));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.setGravity(Gravity.CENTER_VERTICAL);t.addView(txt(title,19,Color.rgb(20,43,76),true));t.addView(txt(sub,14,Color.rgb(91,105,126),false));t.setLayoutParams(new LinearLayout.LayoutParams(0,-1,1));c.addView(t);return c;}
 private void selectPasswordCard(View c,boolean muted){c.setBackground(grad(muted?new int[]{Color.rgb(247,250,255),Color.rgb(241,245,250)}:new int[]{Color.rgb(218,238,255),Color.rgb(232,244,255)},dp(18)));c.setAlpha(muted ? 0.65f : 1f);}
 private void newPin(){EditText a=new EditText(this),b=new EditText(this);a.setHint("סיסמה חדשה");b.setHint("הקלדה חוזרת");a.setInputType(InputType.TYPE_CLASS_NUMBER);b.setInputType(InputType.TYPE_CLASS_NUMBER);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.addView(a);l.addView(b);AlertDialog d=new AlertDialog.Builder(this).setTitle("סיסמה מספרית חדשה").setView(l).setNegativeButton("ביטול",null).setPositiveButton("שמירה",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String n=a.getText().toString(),q=b.getText().toString();if(n.length()<4){a.setError("לפחות 4 ספרות");return;}if(!n.matches("[0-9]+")){a.setError("יש להזין ספרות בלבד");return;}if(!n.equals(q)){b.setError("הסיסמאות אינן זהות");return;}getSharedPreferences(PREFS,0).edit().putString(PASSWORD,n).putString(TYPE,PIN).apply();d.dismiss();Toast.makeText(this,"הסיסמה עודכנה",Toast.LENGTH_SHORT).show();}));d.show();}
 private void newPattern(){patternStep("ציירו סיסמה חדשה",a->patternStep("ציירו שוב לאימות",b->{if(!a.equals(b)){Toast.makeText(this,"התבניות אינן זהות",Toast.LENGTH_LONG).show();newPattern();return;}getSharedPreferences(PREFS,0).edit().putString(PASSWORD,a).putString(TYPE,PATTERN).apply();Toast.makeText(this,"הסיסמה עודכנה",Toast.LENGTH_SHORT).show();}));}
 interface Done{void go(String s);}
 private void patternStep(String title,Done done){PatternLockView p=new PatternLockView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER_HORIZONTAL);c.setPadding(dp(12),dp(4),dp(12),dp(8));TextView i=txt("ציירו את התבנית ולאחר מכן לחצו על אישור והמשך",15,Color.rgb(91,105,126),false);i.setGravity(Gravity.CENTER);c.addView(i,new LinearLayout.LayoutParams(-1,dp(55)));c.addView(p,new LinearLayout.LayoutParams(dp(280),dp(280)));TextView ok=txt("אישור והמשך",17,Color.WHITE,true);ok.setGravity(Gravity.CENTER);ok.setBackground(grad(new int[]{Color.rgb(40,125,225),Color.rgb(61,46,180)},dp(18)));LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,dp(54));op.topMargin=dp(12);c.addView(ok,op);AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setView(c).setNegativeButton("ביטול",null).create();ok.setOnClickListener(v->{String pat=p.getPattern();if(pat.length()<4){Toast.makeText(this,"לפחות 4 נקודות",Toast.LENGTH_SHORT).show();return;}d.dismiss();done.go(pat);});d.show();}
 private void admin(){DevicePolicyManager dm=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);ComponentName comp=new ComponentName(this,SafeStepsDeviceAdminReceiver.class);if(dm.isAdminActive(comp)){new AlertDialog.Builder(this).setTitle("מנהל מכשיר פעיל").setMessage("Safe Steps כבר מוגדרת כמנהלת מכשיר. כדי לבטל אותה, יש לאמת את המנהל ולאחר מכן לבטל את ההרשאה.").setNegativeButton("סגירה",null).setPositiveButton("ביטול הרשאה",(di,w)->credential("ביטול מנהל מכשיר",()->dm.removeActiveAdmin(comp))).show();return;}Intent i=new Intent(DevicePolicyManager.ACTION_ADD_DEVICE_ADMIN);i.putExtra(DevicePolicyManager.EXTRA_DEVICE_ADMIN,comp);i.putExtra(DevicePolicyManager.EXTRA_ADD_EXPLANATION,"מנהל המכשיר מסייע למנוע הסרה רגילה של Safe Steps עד לביטול ההרשאה.");startActivity(i);}
 private void about(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER_HORIZONTAL);c.setPadding(dp(22),dp(12),dp(22),dp(12));TextView i=txt("🛡",62,Color.rgb(40,125,225),true);i.setGravity(Gravity.CENTER);c.addView(i,new LinearLayout.LayoutParams(-1,dp(82)));TextView t=txt("Safe Steps",27,Color.rgb(20,43,76),true);t.setGravity(Gravity.CENTER);c.addView(t,new LinearLayout.LayoutParams(-1,dp(45)));TextView s=txt("צעדים בטוחים בשבילך",17,Color.rgb(40,125,225),true);s.setGravity(Gravity.CENTER);c.addView(s,new LinearLayout.LayoutParams(-1,dp(38)));TextView d=txt("אפליקציה שנועדה לסייע בהגנה על הגדרות המכשיר ולשמור על סביבת שימוש בטוחה.",15,Color.rgb(91,105,126),false);d.setGravity(Gravity.CENTER);c.addView(d,new LinearLayout.LayoutParams(-1,dp(72)));TextView co=txt("© כל הזכויות שמורות לישראל מויאל.\n\nליצירת קשר:\ninm758595@gmail.com",14,Color.rgb(70,92,119),false);co.setGravity(Gravity.CENTER);c.addView(co,new LinearLayout.LayoutParams(-1,dp(72)));new AlertDialog.Builder(this).setView(c).setPositiveButton("סגירה",null).show();}
 private LinearLayout optionCard(String icon,String title,String sub){LinearLayout o=new LinearLayout(this);o.setOrientation(LinearLayout.HORIZONTAL);o.setGravity(Gravity.CENTER_VERTICAL);o.setPadding(dp(14),dp(8),dp(14),dp(8));o.setBackground(grad(new int[]{Color.rgb(235,245,255),Color.rgb(248,251,255)},dp(18)));TextView i=txt(icon,28,Color.rgb(40,125,225),true);i.setGravity(Gravity.CENTER);o.addView(i,new LinearLayout.LayoutParams(dp(58),-1));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setGravity(Gravity.CENTER_VERTICAL);tx.addView(txt(title,18,Color.rgb(20,43,76),true));tx.addView(txt(sub,13,Color.rgb(91,105,126),false));tx.setLayoutParams(new LinearLayout.LayoutParams(0,-1,1));o.addView(tx);TextView a=txt("‹",28,Color.rgb(40,125,225),true);a.setGravity(Gravity.CENTER);o.addView(a,new LinearLayout.LayoutParams(dp(28),-1));return o;}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackground(grad(new int[]{Color.WHITE,Color.rgb(247,250,255)},dp(20)));return c;}
 private Button btn(String t){Button b=new Button(this);b.setText(t);b.setTextSize(16);b.setAllCaps(false);return b;}
 private TextView txt(String t,float s,int col,boolean bold){TextView v=new TextView(this);v.setText(t);v.setTextSize(s);v.setTextColor(col);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 private LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(15);return p;}
 private GradientDrawable grad(int[] c,float r){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,c);d.setCornerRadius(r);return d;}
 private int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+0.5f);}
}